wandb_version: 1

agnostic_nms:
  value: false
augment:
  value: false
batch:
  value: -1
box:
  value: 8.599499959146328
cache:
  value: true
cfg:
  value: null
close_mosaic:
  value: 10
cls:
  value: 9.36717818194814
conf:
  value: null
copy_paste:
  value: 0
cos_lr:
  value: false
data:
  value: yolov8/tt100k_2021_2023-01-05-20-yolo8.yaml
degrees:
  value: 0.04154162896705476
deterministic:
  value: true
device:
  value: auto
dfl:
  value: 0.4576186930808934
dnn:
  value: false
dropout:
  value: 0
dynamic:
  value: false
epochs:
  value: 300
exist_ok:
  value: false
fl_gamma:
  value: 0
fliplr:
  value: 0
flipud:
  value: 0
format:
  value: torchscript
half:
  value: false
hide_conf:
  value: false
hide_labels:
  value: false
hsv_h:
  value: 0.017348485903699223
hsv_s:
  value: 0.8282671066213242
hsv_v:
  value: 0.8015297931234072
hydra:
  value:
    output_subdir: null
    run:
      dir: .
image_weights:
  value: false
imgsz:
  value: 1024
int8:
  value: false
iou:
  value: 0.7
keras:
  value: false
label_smoothing:
  value: 0
line_thickness:
  value: 3
lr0:
  value: 0.0005428342629577344
lrf:
  value: 0.02313400787206201
mask_ratio:
  value: 4
max_det:
  value: 300
mixup:
  value: 0.29928674084770385
mode:
  value: train
model:
  value: yolov8m.pt
momentum:
  value: 0.8856454661762224
mosaic:
  value: 0.7942506202013364
name:
  value: 扫清六合，席卷八方
nbs:
  value: 64
nms:
  value: false
opset:
  value: 17
optimize:
  value: false
optimizer:
  value: AdamW
overlap_mask:
  value: true
patience:
  value: 50
perspective:
  value: 0.0009510075584315388
plots:
  value: true
pretrained:
  value: false
project:
  value: yolo8_traffic_sign
rect:
  value: false
resume:
  value: false
retina_masks:
  value: false
save:
  value: true
save_conf:
  value: false
save_crop:
  value: false
save_hybrid:
  value: false
save_json:
  value: false
save_txt:
  value: false
scale:
  value: 0.4004267872350467
seed:
  value: 0
shear:
  value: 0.0030915580842491783
show:
  value: false
simplify:
  value: false
single_cls:
  value: false
source:
  value: null
task:
  value: detect
translate:
  value: 0.1996435538109461
v5loader:
  value: false
val:
  value: true
verbose:
  value: false
vid_stride:
  value: 1
visualize:
  value: true
warmup_bias_lr:
  value: 0.12015731523684646
warmup_epochs:
  value: 4.661541878696687
warmup_momentum:
  value: 0.7972139539466715
weight_decay:
  value: 0.00068438903153412
workers:
  value: 32
workspace:
  value: 4
